### ISSUE TITLE
please remember increasing versionCode for each release

### ISSUE THREAD

**Issue by IzzySoft** [JobinBiju/Taskly#9]
Just to notify you: todays v1.1.3 identifies with `versionCode: 1001` – the same `versionCode` v1.0.2 already had, so Android will not accept it as update. Please remember to always increase `versionCode` with each new release :wink: Thanks!

**Comment by JobinBiju** [comment]
@IzzySoft I already changed the version number in pubspec.yaml & the app updated just fine. Please elaborate your issue so that i can look into it.

**Comment by IzzySoft** [comment]
Just take the two APKs from releases and run `aapt d badging` against them. You'll see they both report the very same `versionCode`. Your `pubspec.yaml` sets `versionCode` to `1`, which is the initial one:

```yaml
version: 1.1.3+1
```

so you need to increase the value following the `+`. It seems with your configuration, something is just adding `1000` to it. So if for the next version you make this e.g.

```yaml
version: 1.1.4+4
```

(assuming it will be v1.1.4 – and I've picked the `4` as it's your 4th release then), it should be fine: the `1000` gets added again turning it into a `1004`, which is higher than `1001` and thus accepted as update by Android. Cross-checking the resulting APK cannot hurt, though – as pointed out, `aapt d badging *.apk` does the trick. The values you're after should be at the very beginning of the output, and you could eg `grep` for `versionCode`.

**Comment by JobinBiju** [comment]
Thanks for the info @IzzySoft. I have only changed the version_name and didn't change the version_code. I edited the release just now. I tried updating the app before this and it worked just fine. Anyway, I'll update the version codes from now on.

**Comment by IzzySoft** [comment]
Thanks! Looking forward to the next release then.
